### ISSUE TITLE
Failed to queue the build with message : undefined

### ISSUE THREAD

**Issue by corystein** [geeklearningio/gl-vsts-tasks-inception#12]
Getting this message [Failed to queue the build with message : undefined].  Is there something I'm missing?

**Comment by sandorfr** [comment]
Hi @corystein sorry for the inconvience. 

Can you provide the debug logs as described [here](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/wiki/How-to-Report-an-issue) and maybe a screenshot of your settings?

**Comment by sandorfr** [comment]
@corystein any update?

**Comment by sandorfr** [comment]
We are closing this issue as there is not enough information to troubleshoot. Feel free to comment anytime if you need help.
