### ISSUE TITLE
Endpoint not present: SystemVssConnection

### ISSUE THREAD

**Issue by duyhung13** [geeklearningio/gl-vsts-tasks-inception#9]
I tried to use this build step and got the error as below.
Please help to take a look on this issue.
Thanks

`Processing: ##vso[task.debug]loading inputs and endpoints
loading inputs and endpoints
Processing: ##vso[task.debug]loading INPUT_BUILDDEFINITIONSELECTIONMODE
loading INPUT_BUILDDEFINITIONSELECTIONMODE
Processing: ##vso[task.debug]loading INPUT_BUILDDEFINITION
loading INPUT_BUILDDEFINITION
Processing: ##vso[task.debug]loading INPUT_BUILDPARAMETERS
loading INPUT_BUILDPARAMETERS
Processing: ##vso[task.debug]loading INPUT_IGNOREWARNINGS
loading INPUT_IGNOREWARNINGS
Processing: ##vso[task.debug]loading ENDPOINT_AUTH_0946ef9e-4410-4da7-97a2-597982814703
loading ENDPOINT_AUTH_0946ef9e-4410-4da7-97a2-597982814703
Processing: ##vso[task.debug]loading ENDPOINT_AUTH_SCHEME_0946ef9e-4410-4da7-97a2-597982814703
loading ENDPOINT_AUTH_SCHEME_0946ef9e-4410-4da7-97a2-597982814703
Processing: ##vso[task.debug]loading ENDPOINT_AUTH_PARAMETER_0946ef9e-4410-4da7-97a2-597982814703_ACCESSTOKEN
loading ENDPOINT_AUTH_PARAMETER_0946ef9e-4410-4da7-97a2-597982814703_ACCESSTOKEN
Processing: ##vso[task.debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
Processing: ##vso[task.debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
Processing: ##vso[task.debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
Processing: ##vso[task.debug]loaded 10
loaded 10
Processing: ##vso[task.debug]System.DefinitionId=6
System.DefinitionId=6
Processing: ##vso[task.debug]Current Build Id : 6
Current Build Id : 6
Processing: ##vso[task.debug]Getting credentials for local feeds
Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
Processing: ##vso[task.debug]SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
Processing: ##vso[task.debug]Got auth token
Got auth token
Processing: ##vso[task.debug]task result: Failed
task result: Failed
Processing: ##vso[task.issue type=error;]Unhandled: Endpoint not present: SystemVssConnection
Unhandled: Endpoint not present: SystemVssConnection
Processing: ##vso[task.complete result=Failed;]Unhandled: Endpoint not present: SystemVssConnection`

**Comment by sandorfr** [comment]
Hi,

I'm sorry to hear that. Can you provide me a few details ?
- Are you running this on Premise or on vsts
- Are you using hosted build agent or your own build agent
- If you are using your own build agent are you using the old one or the new xplat one

Warm regards, 
Cyprien

**Comment by sandorfr** [comment]
@duyhung13 , I think there was an issue with the casing of the endpoint name on my build. I pushed the fix, can you tell me if it work now? 

I'm still interested in answers to my questions above.

**Comment by duyhung13** [comment]
@sandorfr wow, amazing fixed. It's work now. 
Thanks a lot 

FYI,
    Are you running this on Premise or on vsts
=> I tried on vsts and my local TFS15 RC2
    Are you using hosted build agent or your own build agent
=> I used hosted build and my build agent 
    If you are using your own build agent are you using the old one or the new xplat one
=> I think it's latest version because I just down it from vsts agent pool

**Comment by sandorfr** [comment]
Thanks for reporting this, the answers, the feedback and the nice review :) !

**Comment by duyhung13** [comment]
@sandorfr No problem, your build task is exactly what I want so I just want to give my feedback to improve it.

Besides, I just created an enhancement at https://github.com/geeklearningio/gl-vsts-tasks-inception/issues/10

Please help to take a look if you have time

**Comment by sandorfr** [comment]
I think endpoint name is case sensitive on very specific version/platforms,
I pushed a fix can you telle me if it's working for you?

**Comment by duyhung13** [comment]
@sandorfr as confirmed from my team, it works properly without any problem :)

**Comment by sandorfr** [comment]
Yes this was an old mail response stuck in the web for days :)

**Comment by duyhung13** [comment]
haha, it's ok for me :D
